# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0emessages.proto\x12\x07\x64\x65\x65spee"\x99\x01\n\x0c\x41gentRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x35\n\x08metadata\x18\x03 \x03(\x0b\x32#.deespee.AgentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\\\n\rAgentResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t"V\n\nBidRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x04user\x18\x02 \x01(\x0b\x32\r.deespee.User\x12\x1f\n\x06\x64\x65vice\x18\x03 \x01(\x0b\x32\x0f.deespee.Device"\x12\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t" \n\x06\x44\x65vice\x12\n\n\x02ua\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t"7\n\x0b\x42idResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x62idid\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02"W\n\tDspAction\x12\x11\n\taction_id\x18\x01 \x01(\t\x12\x18\n\x10\x61gent_request_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t"T\n\tDmpUpdate\x12\x11\n\tupdate_id\x18\x01 \x01(\t\x12\x18\n\x10\x61gent_request_id\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\tB0Z.github.com/karolsudol/deespee/adexchange/protob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "messages_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z.github.com/karolsudol/deespee/adexchange/proto"
    _AGENTREQUEST_METADATAENTRY._options = None
    _AGENTREQUEST_METADATAENTRY._serialized_options = b"8\001"
    _AGENTREQUEST._serialized_start = 28
    _AGENTREQUEST._serialized_end = 181
    _AGENTREQUEST_METADATAENTRY._serialized_start = 134
    _AGENTREQUEST_METADATAENTRY._serialized_end = 181
    _AGENTRESPONSE._serialized_start = 183
    _AGENTRESPONSE._serialized_end = 275
    _BIDREQUEST._serialized_start = 277
    _BIDREQUEST._serialized_end = 363
    _USER._serialized_start = 365
    _USER._serialized_end = 383
    _DEVICE._serialized_start = 385
    _DEVICE._serialized_end = 417
    _BIDRESPONSE._serialized_start = 419
    _BIDRESPONSE._serialized_end = 474
    _DSPACTION._serialized_start = 476
    _DSPACTION._serialized_end = 563
    _DMPUPDATE._serialized_start = 565
    _DMPUPDATE._serialized_end = 649
# @@protoc_insertion_point(module_scope)
