# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x07\x64\x65\x65spee\"\x99\x01\n\x0c\x41gentRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x35\n\x08metadata\x18\x03 \x03(\x0b\x32#.deespee.AgentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\rAgentResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\"W\n\tDspAction\x12\x11\n\taction_id\x18\x01 \x01(\t\x12\x18\n\x10\x61gent_request_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"T\n\tDmpUpdate\x12\x11\n\tupdate_id\x18\x01 \x01(\t\x12\x18\n\x10\x61gent_request_id\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGENTREQUEST_METADATAENTRY._options = None
  _AGENTREQUEST_METADATAENTRY._serialized_options = b'8\001'
  _AGENTREQUEST._serialized_start=28
  _AGENTREQUEST._serialized_end=181
  _AGENTREQUEST_METADATAENTRY._serialized_start=134
  _AGENTREQUEST_METADATAENTRY._serialized_end=181
  _AGENTRESPONSE._serialized_start=183
  _AGENTRESPONSE._serialized_end=275
  _DSPACTION._serialized_start=277
  _DSPACTION._serialized_end=364
  _DMPUPDATE._serialized_start=366
  _DMPUPDATE._serialized_end=450
# @@protoc_insertion_point(module_scope)
